language: python
python:
- "3.6"

env:
  global:
    # Doctr deploy key for areaDetector/areaDetector.github.io
    - secure: "lczsvkSIMVqEVGYNsE+vHhjDuSXub5VnA92uVk8CrC36xHHo8n8xfpouUcnIbvcAvtVM5azKnw9l98sb//4B1lcJD7QqJ9SyW10TBFH9UO/1N5Gh0wfKet17aqRVm18Ry8qdjYUQvacMHw60yjyZbf/ro9AKapkVDainb5D3JSQ="

script:
  - set -e
  - pip install -r requirements.txt
  - cd docs
  - make html
  - doctr deploy --built-docs _build/html --deploy-repo areaDetector/areaDetector.github.io .

