language: python
python:
- "3.6"

env:
  global:
    # Doctr deploy key for areaDetector/areaDetector.github.io
    - secure: "Wh/lPpT7M8M2Bdbv/6RRcc+381QsVoNylC+hZwMoXT5iw6mGRccxK2W3t27IVrKA7PWyTFPwG3mo9Y+jtHVm9POfgAH0Z1rx2s1n6u14423Am5Vw2uehoZfKhmGbwt1j/7wtqEzRj60yMsNFroYXNJHTiRmyXzHuqUYV1R9kzq0="

script:
  - set -e
  - pip install -r requirements.txt
  - cd docs
  - make html
  - cd ..
  - pip install git+git://github.com/drdoctr/doctr.git
  - doctr deploy --key-path github_deploy_key_areadetector_areadetector_github_io.enc --built-docs docs/_build/html --deploy-repo areaDetector/areaDetector.github.io docs

